### ISSUE TITLE
vl_simplenn_tidy.m is missing

### ISSUE THREAD

**Issue by waleedt** [liuyang12/PnP-SCI#1]
Hi,

I downloaded the PnP-SCI repository and datasets, as detailed in the readme/usage. However, I am not able to run test_pnpsci or test_pnpsci_largescale. It seems some m-files are missing. Following are the errors that I receive:

**test_pnpsci_largescale**

>> test_pnpsci_largescale('football')
Unrecognized function or variable 'vl_simplenn_tidy'.

Error in test_pnpsci_largescale (line 70)
  para.net = vl_simplenn_tidy(net);

**test_pnpsci**

>> test_pnpsci
GAP-TV Reconstruction frame-block 1 of 4 ...
  GAP-TV iteration    5, sigma  10, PSNR 16.51 dB.
  GAP-TV iteration   10, sigma  10, PSNR 19.71 dB.
  GAP-TV iteration   15, sigma  10, PSNR 22.20 dB.
  GAP-TV iteration   20, sigma  10, PSNR 23.94 dB.
  GAP-TV iteration   25, sigma  10, PSNR 25.07 dB.
  GAP-TV iteration   30, sigma  10, PSNR 25.81 dB.
  GAP-TV iteration   35, sigma  10, PSNR 26.31 dB.
  GAP-TV iteration   40, sigma  10, PSNR 26.66 dB.
  GAP-TV iteration   45, sigma  10, PSNR 26.92 dB.
  GAP-TV iteration   50, sigma  10, PSNR 27.11 dB.
  GAP-TV iteration   55, sigma  10, PSNR 27.24 dB.
  GAP-TV iteration   60, sigma  10, PSNR 27.35 dB.
  GAP-TV iteration   65, sigma  10, PSNR 27.42 dB.
  GAP-TV iteration   70, sigma  10, PSNR 27.48 dB.
  GAP-TV iteration   75, sigma  10, PSNR 27.53 dB.
  GAP-TV iteration   80, sigma  10, PSNR 27.57 dB.
  GAP-TV iteration   85, sigma  10, PSNR 27.59 dB.
  GAP-TV iteration   90, sigma  10, PSNR 27.62 dB.
  GAP-TV iteration   95, sigma  10, PSNR 27.64 dB.
  GAP-TV iteration  100, sigma  10, PSNR 27.65 dB.
GAP-TV Reconstruction frame-block 2 of 4 ...
  GAP-TV iteration    5, sigma  10, PSNR 16.08 dB.
  GAP-TV iteration   10, sigma  10, PSNR 19.08 dB.
  GAP-TV iteration   15, sigma  10, PSNR 21.35 dB.
  GAP-TV iteration   20, sigma  10, PSNR 22.93 dB.
  GAP-TV iteration   25, sigma  10, PSNR 24.01 dB.
  GAP-TV iteration   30, sigma  10, PSNR 24.77 dB.
  GAP-TV iteration   35, sigma  10, PSNR 25.32 dB.
  GAP-TV iteration   40, sigma  10, PSNR 25.70 dB.
  GAP-TV iteration   45, sigma  10, PSNR 25.98 dB.
  GAP-TV iteration   50, sigma  10, PSNR 26.18 dB.
  GAP-TV iteration   55, sigma  10, PSNR 26.32 dB.
  GAP-TV iteration   60, sigma  10, PSNR 26.42 dB.
  GAP-TV iteration   65, sigma  10, PSNR 26.50 dB.
  GAP-TV iteration   70, sigma  10, PSNR 26.55 dB.
  GAP-TV iteration   75, sigma  10, PSNR 26.59 dB.
  GAP-TV iteration   80, sigma  10, PSNR 26.62 dB.
  GAP-TV iteration   85, sigma  10, PSNR 26.65 dB.
  GAP-TV iteration   90, sigma  10, PSNR 26.67 dB.
  GAP-TV iteration   95, sigma  10, PSNR 26.68 dB.
  GAP-TV iteration  100, sigma  10, PSNR 26.69 dB.
GAP-TV Reconstruction frame-block 3 of 4 ...
  GAP-TV iteration    5, sigma  10, PSNR 16.11 dB.
  GAP-TV iteration   10, sigma  10, PSNR 19.20 dB.
  GAP-TV iteration   15, sigma  10, PSNR 21.52 dB.
  GAP-TV iteration   20, sigma  10, PSNR 23.03 dB.
  GAP-TV iteration   25, sigma  10, PSNR 23.96 dB.
  GAP-TV iteration   30, sigma  10, PSNR 24.54 dB.
  GAP-TV iteration   35, sigma  10, PSNR 24.94 dB.
  GAP-TV iteration   40, sigma  10, PSNR 25.23 dB.
  GAP-TV iteration   45, sigma  10, PSNR 25.45 dB.
  GAP-TV iteration   50, sigma  10, PSNR 25.62 dB.
  GAP-TV iteration   55, sigma  10, PSNR 25.74 dB.
  GAP-TV iteration   60, sigma  10, PSNR 25.85 dB.
  GAP-TV iteration   65, sigma  10, PSNR 25.93 dB.
  GAP-TV iteration   70, sigma  10, PSNR 25.99 dB.
  GAP-TV iteration   75, sigma  10, PSNR 26.04 dB.
  GAP-TV iteration   80, sigma  10, PSNR 26.08 dB.
  GAP-TV iteration   85, sigma  10, PSNR 26.11 dB.
  GAP-TV iteration   90, sigma  10, PSNR 26.14 dB.
  GAP-TV iteration   95, sigma  10, PSNR 26.16 dB.
  GAP-TV iteration  100, sigma  10, PSNR 26.18 dB.
GAP-TV Reconstruction frame-block 4 of 4 ...
  GAP-TV iteration    5, sigma  10, PSNR 16.01 dB.
  GAP-TV iteration   10, sigma  10, PSNR 18.83 dB.
  GAP-TV iteration   15, sigma  10, PSNR 20.86 dB.
  GAP-TV iteration   20, sigma  10, PSNR 22.18 dB.
  GAP-TV iteration   25, sigma  10, PSNR 23.04 dB.
  GAP-TV iteration   30, sigma  10, PSNR 23.63 dB.
  GAP-TV iteration   35, sigma  10, PSNR 24.05 dB.
  GAP-TV iteration   40, sigma  10, PSNR 24.35 dB.
  GAP-TV iteration   45, sigma  10, PSNR 24.58 dB.
  GAP-TV iteration   50, sigma  10, PSNR 24.74 dB.
  GAP-TV iteration   55, sigma  10, PSNR 24.86 dB.
  GAP-TV iteration   60, sigma  10, PSNR 24.96 dB.
  GAP-TV iteration   65, sigma  10, PSNR 25.03 dB.
  GAP-TV iteration   70, sigma  10, PSNR 25.08 dB.
  GAP-TV iteration   75, sigma  10, PSNR 25.12 dB.
  GAP-TV iteration   80, sigma  10, PSNR 25.15 dB.
  GAP-TV iteration   85, sigma  10, PSNR 25.18 dB.
  GAP-TV iteration   90, sigma  10, PSNR 25.20 dB.
  GAP-TV iteration   95, sigma  10, PSNR 25.21 dB.
  GAP-TV iteration  100, sigma  10, PSNR 25.23 dB.
GAP-TV mean PSNR 26.45 dB, mean SSIM 0.8448, total time  41.5 s.
Unrecognized function or variable 'vl_simplenn_tidy'.

Error in test_pnpsci (line 81)
  para.net = vl_simplenn_tidy(net);

**Comment by liuyang12** [comment]
I think [MatConvNet](https://www.vlfeat.org/matconvnet/ 'MatConvNet') is missing here, since it is required to apply FFDNet as a denoser. Please refer to the [doc](https://www.vlfeat.org/matconvnet/install/#compiling 'compiling MatConvNet') to compile it (with CUDA and CuDNN for better performance on GPU). *You might find [this issue](https://github.com/vlfeat/matconvnet/issues/1143 'Problem Compiling with GPU Support on MATLAB 2018a') useful if you compile it on MATLAB 2018a and above.* 

I will try to release the real data and Python (PyTorch) version hopefully after we complete the journal version.

**Comment by waleedt** [comment]
Problem resolved. MatConvNet was missing. Thank you very much!

**Comment by Diyorazh** [comment]
May I ask if we need to run on GPU in order to reproduce some results? -- Thanks!

**Comment by liuyang12** [comment]
GPU is not needed to reproduce the same results in terms of reconstruction quality. You can set `para.useGPU = false;` in [line#82](https://github.com/liuyang12/PnP-SCI/blob/91fc7aa48ffc544256a9663e9a2e4d0e195b93e6/test_pnpsci.m#L82) of `test_pnpsci.m`to use your local CPU for running the pre-trained network. However, [MatConvNet](https://www.vlfeat.org/matconvnet/) is required for running the MATLAB version of FFDNet. Sadly, MatConvNet only supports up to CUDA 10 and is no longer maintained. You may check the [Python version](https://github.com/liuyang12/PnP-SCI_python) (PyTorch is used) works on CPU only as well (Ooops, I need to update the readme of [PnP-SCI_python](https://github.com/liuyang12/PnP-SCI_python)). Again, you need to set `useGPU = False` in [line#183](https://github.com/liuyang12/PnP-SCI_python/blob/9a9eae5d8c357d6bf0e8b808f9dd2af45d00e85a/pnp_sci_video_grayscale_benchmark.py#L183) of `pnp_sci_video_grayscale_benchmark.py` or multiple lines of `pnp_sci_video_middle_scale_color.py`.

**Comment by Diyorazh** [comment]
@liuyang12 Thank you! super clear. I have already starred and cloned your python version. It can be a great help to my course project. Thank you!
